[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "/api"

[[redirects]]
  from = "/api/*"
  to = "https://d353mi06zxxkvl.cloudfront.net/api/:splat"
  status = 200
  force = true

  [redirects.headers]
    X-From = "Netlify"
