[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://trucking-tms-alb-1848896522.us-east-1.elb.amazonaws.com/api"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
