[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_API_URL = "http://trucking-tms-alb-1848896522.us-east-1.elb.amazonaws.com/api"
