[build]
  base = "frontend"
  command = "npm run build-and-export"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false"

# Redirect API calls to your AWS backend
[[redirects]]
  from = "/api/*"
  to = "http://18.212.79.137:8000/api/:splat"
  status = 200

# Redirect all other requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build-and-export"

[context.deploy-preview]
  command = "npm run build-and-export"

[context.branch-deploy]
  command = "npm run build-and-export"